### ISSUE TITLE
Quantities

### ISSUE THREAD

**Issue by Krognol** [Krognol/go-pure#1]
Quantities currently assume that the value is one or more numbers followed by one or more letter/symbols (which can be followed by another number).

Needs a better way of declaring what is the value and what is the unit.

**Comment by ghost** [comment]
This assumption is correct. A unit may very well contain digits, such as "2 km^2".

The value is the initial digits, the rest is the unit. Some people wanted floating point values, but I'm personally fine with leaving that for 2.0 (one can always scale with units)

**Comment by Krognol** [comment]
@pureconfig Floating point values shouldn't be a problem to implement. And since this is how quantities are supposed to work, I will leave it as it is.

Closing this issue.
